### ISSUE TITLE
Implementing own filters outside the warp

### ISSUE THREAD

**Issue by katyo** [seanmonstar/warp#123]
I think warp provides pretty useable way to build server-side of web-applications, maybe best easy and flexible at the moment.

So I would like to be able implement some application-specific filters but as I see the `filter` submodule is private. So users doesn't access to some useful functions like `filter_fn` which helps to implement new filters.

Why is it so and how can I create new filters?

**Comment by katyo** [comment]
I found what I can use `any()` as a start point to create my own filter.

**Comment by norcalli** [comment]
@katyo you should close this issue if your problem is solved then.

Although I have wondered if there is a way to discard the `Extract` from `any`? I wanted to create a filter to simply dump the incoming request headers, so I did `warp::any().map(|_| /* dump */)` which maps to `()`, but in the next map that I did for the actual route logic, I still had to accept the `()` as a parameter. Is there a way to do this with `any` and the existing combinators, or do we need a `null` filter?

**Comment by seanmonstar** [comment]
@norcalli see #3 about that (and comment if you have thoughts!).
