### ISSUE TITLE
Allow getting request path tail

### ISSUE THREAD

**Issue by lnicola** [seanmonstar/warp#13]
Like this: https://rocket.rs/guide/requests/#multiple-segments

**Comment by seanmonstar** [comment]
Nothing prevents there being both `warp::path::segments()` and `warp::path::tail()`!

For the tail, it'd be nice if it could just return the `&str` of the path, but I don't think that can work, since the compiler can't prove that the future doesn't live longer than the request (maybe `async` will allow this?). So for now, it could return a newtype, `struct Tail(http::uri::PathAndQuery, usize)` that can be used to grab the `&str`.
