### ISSUE TITLE
[Question] routing priority

### ISSUE THREAD

**Issue by Geobert** [seanmonstar/warp#203]
Hi,

I have these endpoints:
```rust
// POST /store
    let create_store = warp::path("store")
        .and(warp::header::<String>(HEADER_AUTH))
        .and(warp::body::json())
        .and_then(|auth, obj| {
            store::create_store(auth, obj)
                .and_then(|store_id| Ok(warp::reply::json(&store_id)))
                .or_else(|e| Err(warp::reject::custom(e.compat())))
        });

// POST /aisle
    let create_aisle = path!("store" / u32 / "aisle")
        .and(warp::header::<String>(HEADER_AUTH))
        .and(warp::body::json())
        .and_then(|store_id, auth, obj| {
            aisle::create_aisle(auth, store_id, obj)
                .and_then(|aisle| Ok(warp::reply::json(&aisle)))
                .or_else(|e| Err(warp::reject::custom(e.compat())))
        });

let post_routes = warp::post2()
        .and(
            create_user
                .or(login)
                .or(logout)
                .or(create_store)
                .or(create_aisle)
                .or(nuke),
        )
        .recover(customize_error);

```

When querying "/store/1/aisle", `create_store` is responding instead of `create_aisle`. Am I missing something or do I need to put them in a proper order myself (as inverting `create_aisle` and `create_store` works).

Thanks!

**Comment by hgzimmerman** [comment]
Warp will attempt to routes in the order specified by your filters. It just so happens that both `create_aisle` and `create_store` match "/store/:u32/aisle". This is because warp matches paths in the most permissive way possible, so for `create_store`, it will match "/store/and/any/other/thing/after/store". To prevent any other path segments from matching, you need to terminate your path in `create_store` with an `and([warp::filters::path::end()]`. [docs](https://docs.rs/warp/0.1.15/warp/filters/path/fn.end.html).

**Comment by Geobert** [comment]
I understand! Thank you very much!
