### ISSUE TITLE
Add support for custom keepalive comments in SSE

### ISSUE THREAD

**Issue by codesections** [seanmonstar/warp#204]
The current SSE filter has a `keep` function that sends a keepalive comment every interval.  Right now, that comment is hard-coded as `:`.

I would like to add support for a custom comment as the keepalive message (as a third parameter to `keep`).  The [relevant portion of the spec](https://www.w3.org/TR/2009/WD-eventsource-20090421/#notes) states that "authors can include a comment line (one **starting with** a ':' character) every 15 seconds or so" (emphasis supplied).  Thus, it's compliant with the spec to have a custom message.

My use case is that I'm porting over an existing API, and it's current SSE heartbeat message is `:thump`; I'd prefer to port that over without changing the message.

If you'd be open to a PR along these lines, I would be happy to work on something—I believe it would be a minor change.

If you would prefer, we could add a `keep_with_message` function to avoid changing the function signature of `keep`.  (Or a `keep2`.)

**Comment by seanmonstar** [comment]
That sounds reasonable. Looking over the API again, perhaps `keepalive` (or `keep_alive`?) would be a clearer name over `keep`? In that sense, we could add the second version with the new name (and not need the uglier `keep2`), deprecating `keep`.

What sort of argument would make sense? It'd be nice to be able to easily pass the default...

**Comment by codesections** [comment]
I terms of being able to easily pass the default, it seems like the typical go-to solution is the builder pattern.  That would suggest an API along the following lines:

```rust
keep_alive::from(stream);
```
as the default, and
```rust
keep_alive::from(stream)
    .with_duration(30)
    .with_text("thump".to_string());
```
as the custom.  (One related change implicit in that suggested API is to have the duration take an integer number of seconds rather than an `impl Into<Option<Duration>>`.  It seems like overkill to require users to pull in the `Duration` module given that keep-alive durations will necessarily be some number of seconds rather than, say, hours or days.)

Let me know if you'd like any changes to that API.

**Comment by seanmonstar** [comment]
Sure, a builder pattern seems fine. I'd suggest not having the `from` part, but rather instead of how it currently returns an `impl Stream`, return the `SseKeepAlive` type directly, and add methods that consume `self` to adjust the duration and text.

I think keeping with `Duration` may be the right thing for now, because `Duration::from_secs(30)` is clear, where as APIs that take just some `u32` for duration are often confusing (is it seconds? milliseconds?). However, changing to builder pattern means no needing the `Option` part, which as I read through, is also confusing. I'd assume a `None` duration to mean no interval, but no interval doesn't make sense for a repeating keep-alive...
