### ISSUE TITLE
Using the `impl Filter` return syntax breaks `.or` because of `Clone` requirement

### ISSUE THREAD

**Issue by TheSilvus** [seanmonstar/warp#218]
The following example does not compile:

```rust
extern crate warp;

use warp::{filters::BoxedFilter, Filter, Rejection, Reply};

// Option 1: BoxedFilter
pub fn assets_filter() -> impl Filter<Extract = (impl Reply,), Error = Rejection> {
    warp::path("assets").and(warp::fs::dir("./assets")).boxed()
}

// Option 2: impl Filter
pub fn index_filter() -> impl Filter<Extract = (&'static str,), Error = Rejection> {
    warp::path::end().map(|| "Index page")
}

pub fn main() {
    let routes = assets_filter().or(index_filter());
    warp::serve(routes).run(([127, 0, 0, 1], 3030));
}
```
(Based on example `returning.rs`)

This is because the compiler cannot infer that `index_filter()` implements `Clone`. It can be fixed by either adding an additional  `+ Clone` requirement to the return value or use `.boxed()` on the returned filter. 

This should probably either be changed in the examples (`returning.rs` requires this as well when switching the order of filters in the `or` call) and documented or, what could be a better solution, require `Clone` on `Filter` since it seems to be required almost everywhere - although I do not know enough about the internals to judge this.

**Comment by seanmonstar** [comment]
This is a good point, thanks for bringing it up! I've also noticed that forgetting to add `+ Clone` can be an easy mistake to make. I considered requiring `trait Filter: Clone`, but so far didn't for these reasons:

- The `Clone` trait isn't object-safe, so having it as a super trait would prevent `Box<dyn Filter>`.
- Not *all* filters need to be cloned, only if they are part of a chain... though realistically, they usually need to be.

To get around the object-safety aspect, instead of requiring `trait Filter: Clone`, warp could add some `trait FilterClone { fn clone_box(&self) -> Box<Self>; }` or something, auto-implemented for all `T: Filter + Clone`...
