### ISSUE TITLE
Add `into_bytes()` to the `FullBody`

### ISSUE THREAD

**Issue by application-developer-DA** [seanmonstar/warp#245]
Currently the `FullBody` only gives you access via `Buf`. Unfortunately it's a bit cumbersome to convert it to the `Vec<u8>` representing the full body without the knowledge that it uses the `hyper::Chunk` inside which in turn relies on `bytes::Bytes`.

I've read a comment to the `FullBody` that it was done to support non-contiguous memory slices in future, but does it make any sense? If I were to use `hyper` I would expect `response.into_body().concat2().into_bytes()` to return the full vector of bytes which I can use. Currently `warp` basically does the same thing, but tries to conceal the underlying storage / does not allow us to call `into_bytes()`.

I'm not sure if support of multiple non-contiguous slices would make much sense at this place as if I'm interested in a "body stream", there is already a filter for that in `warp`. I would expect that `concat2()` has the same semantics as in `hyper` with a possibility to eventually make a call to `into_bytes()`.

NB: The change is trivial and I would make it, I'm just not sure if you would be ok with such changes.

**Comment by seanmonstar** [comment]
The purpose of having a separate type is that I'd eventually like to use something that *isn't* `concat2`, because that can force a bunch of copies as the bytes are forced into a single buffer. Something like `collect`, but instead of just a `Vec<Bytes>`, it'd be an `impl Buf`. That trait allows a user to deal with non-contiguous buffers easily, and some basic tests show it to be much more performance.

And one can also serialize to a single buffer via `Vec::from_buf`.

**Comment by application-developer-DA** [comment]
Alright, sounds reasonable.

I just was not quite sure about the difference between `stream` and `concat`. When I got it right now, the `concat` is meant to return a concatenated body and separate "body chunks" might be placed in non-contiguous buffers, whereas `stream` always returns the same "body chunks" as a `Stream` of `Chunks`.
