### ISSUE TITLE
Instructions on how to create modular interfaces?

### ISSUE THREAD

**Issue by droundy** [seanmonstar/warp#246]
I find warp easy to use to create a stand alone website, but am having trouble creating modular things, due to the extreme use of sealed traits.  Is there (or could there be) a guide on what *can* be done?

I've run been trying to write a simple ACME wrapper for lets_encrypt, but can't create accept a `Filter` as an argument, and if I do accept a Filter and then try to use `or` with it, then run into another sealed type, `CombineRejection`.

Is the policy that we simply cannot write and share filters, or functions that use them?

I'd love to see documentation about this, explaining how to create things that work with warp that others could use.  Right now it seems like the documentation is all about creating a single monolithic website.

**Comment by seanmonstar** [comment]
Sorry some of the pieces are so locked down and cryptic, it was one part experiment of sealing things, and one part because I wanted to reduce the amount of breaking changes that users would have to deal with.

The `CombineRejection` thing is kinda janky, it's basically a type system hack to allow propagating the `warp::Never` return type of _some_ filters that will never fail (like, getting the `http::Method`). I found that with this propagation, the compiler was able to eliminate more branches when optimizing.

I believe you should be able to just accept `F: Filter<Error = warp::Rejection>` instead of worrying about `CombineRejections`.

**Comment by droundy** [comment]
Thanks! That was the information that I needed. I'll leave this issue open since I do think there needs to be information in the documentation about how to do this kind of thing.  Maybe when the `!` type lands in stable you can make this prettier...

**Comment by droundy** [comment]
Thanks, that worked!
