### ISSUE TITLE
custom error for path param

### ISSUE THREAD

**Issue by hwchen** [seanmonstar/warp#255]
Hello,

When parsing the param where I have a custom type, e.g. `path!(api / MyParam)`, it seems like any error in parsing will result in `Rejection(NotFound)`. Is it possible for the parsing error to be passed down so that I can deal with it in `.recover()`?

Thanks!

**Comment by seanmonstar** [comment]
There exists [`warp::path::param2`](https://docs.rs/warp/0.1.17/warp/filters/path/fn.param2.html) currently, but I think it needs some tweaks. But instead of boring you with those without asking, you could try `warp::path(api).and(warp::path::param2::<MyParam>())`. The error will be in the `Rejection::cause()`.

**Comment by hwchen** [comment]
Awesome, worked perfectly.

I'm curious what you think the tweaks need to be.

**Comment by seanmonstar** [comment]
- A better name, since I don't expect it to *replace* `param`.
- It probably shouldn't return a `NOT_FOUND` rejection with the error as a cause, but just the custom error as the direct rejection.

**Comment by hwchen** [comment]
I’ve also had a hard time coming up with a good name :) . I guess it should somehow convey `param_with_explicit_err`, but shorter.
