### ISSUE TITLE
"self" in README snippet code

### ISSUE THREAD

**Issue by harscoet** [seanmonstar/warp#261]
What's the purpose of "self" in README snippet code?

```rust
use warp::{self, path, Filter}; // self seem's to be useless?

fn main() {
    let hello = path!("hello" / String).map(|name| format!("Hello, {}!", name));

    warp::serve(hello).run(([127, 0, 0, 1], 3030));
}

```

**Comment by hgzimmerman** [comment]
The `use warp::{self};` is equivalent to just `use warp;`

This enables the `warp::serve(hello)...`. While it is possible to import free functions directly, its a common style choice to import the module where they are from instead to prevent name collisions as well as to provide context.

**Comment by harscoet** [comment]
Ok but examples doesn't seem to use this style, I'm pretty new in rust ecosystem so it's difficult for me to be sure to use the correct style guide.

from https://github.com/seanmonstar/warp/blob/master/examples/hello.rs
```rust
#![deny(warnings)]
extern crate warp;

use warp::Filter;

fn main() {
    // Match any request and return hello world!
    let routes = warp::any().map(|| "Hello, World!");

    warp::serve(routes).run(([127, 0, 0, 1], 3030));
}
```

**Comment by hgzimmerman** [comment]
Rust's 2018 edition removed the need for `extern crate <cratename>` imports, in exchange for having to specify the crate in a `use` statement in order to get the same effect. `extern crate` wasn't removed because doing so without a lengthy deprecation period would have broken everything.

You are correct in that it could be done either way, although there is typically preference for the 2018 edition import system. There is an open PR [here](https://github.com/seanmonstar/warp/pull/234) to transition this crate to the 2018 edition.

**Comment by harscoet** [comment]
> The `use warp::{self};` is equivalent to just `use warp;`
> 
> This enables the `warp::serve(hello)...`. While it is possible to import free functions directly, its a common style choice to import the module where they are from instead to prevent name collisions as well as to provide context.

Reading your comment, I have feeling that I *need* to import "warp" and equivalent syntax should be
```rust
use warp;
use warp::{path, Filter};
```
But in 2018 edition, it seems to be valid (it compiles)
```rust
use warp::{path, Filter};
```
Anyways thanks for explanations :)
