### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by Timmmm** [seanmonstar/warp#276]
It can be hard to know what to put in a Readme, so I thought you might appreciate these things that I immediately wondered but it didn't answer:

1. Does it work on stable?
2. What is its concurrency model? Thread pool? Async/await? (**Edit**: Actually it does say "Asynchronous", but maybe you could expand on that..., e.g. what executor does it use?)
3. How do you deal with global shared state, e.g. an in-memory database (this always seems to be the trickiest part of Rust web frameworks)?

Also, but less critically:

1. Does it support LetsEncrypt easily (like Caddy)?

**Comment by seanmonstar** [comment]
Thanks for the suggestions!

> Does it work on stable?

I'd expect all things to work on stable unless stated specifically. Otherwise, the majority of libraries would need to say this, when it should just be expected, no?

> Actually it does say "Asynchronous", but maybe you could expand on that..., e.g. what executor does it use?

By default, it uses Tokio.

> How do you deal with global shared state

While tricky, my initial feeling is that seems fairly specific, better for the docs/examples, and not something that you'd find when just reading "what the heck is this project", no? For reference, it's touched on in the [docs here](https://docs.rs/warp/0.1.*/warp/filters/any/fn.any.html) and an [example here](https://github.com/seanmonstar/warp/blob/master/examples/todos.rs#L44-L47), but it probably could use some more explaining.

**Comment by Timmmm** [comment]
> Otherwise, the majority of libraries would need to say this, when it should just be expected, no?

I would say in general yes, but several web frameworks require nightly or did until very recently.

> While tricky, my initial feeling is that seems fairly specific

Sort of, but I think *most* real world applications (like TodoMVC!) will need it. And since it is probably the trickiest bit I think it is worth highlighting.

Another tricky bit is websockets & server-sent events, but I see you have a nice example for that and I don't think it is needed in 90% of apps so probably doesn't need anything more.
