### ISSUE TITLE
Expose `Never` in public API.

### ISSUE THREAD

**Issue by dylanede** [seanmonstar/warp#297]
Currently functions returning `impl Filter<Extract = ..., Error = warp::never::Never>` cannot be written by the user, preventing them from returning irrefutable filters from functions.

**Comment by jxs** [comment]
have you tried using `futures::never::Never`? there's an example which uses it :https://github.com/seanmonstar/warp/blob/master/examples/sse.rs#L3
I think the reason warp uses its own `Never` type is because Infalible doesn't implement `std::error::Error`. 
hmm but since warp implements `Reject` for `Never` `crate::never::Never`can maybe be replaced with `futures::never::Never`

**Comment by taiki-e** [comment]
> I think the reason warp uses its own `Never` type is because Infalible doesn't implement `std::error::Error`.

Infalible implements `std::error::Error` via [`std::string::ParseError`](https://doc.rust-lang.org/nightly/std/string/type.ParseError.html).
https://github.com/rust-lang-nursery/futures-rs/pull/1681#discussion_r303720764

**Comment by jxs** [comment]
ah nice then, thanks @taiki-e! i can submit a PR to address this

**Comment by dylanede** [comment]
@jxs that PR looks like it should solve the problem. Regarding your first suggestion, I can't use a different `Never` type from warp in the return signature of my function because I am returning the result of `warp::any().map(...)`, which has the error type `warp::never::Never`.

**Comment by jxs** [comment]
resolved with #298
