### ISSUE TITLE
warp::path requires &'static str

### ISSUE THREAD

**Issue by phyber** [seanmonstar/warp#31]
Hi,

I'm attempting to use this crate in a project where some of the paths to route aren't known until runtime, as they're acquired from the CLI via `clap`. Unfortunately, this appears to mean that I cannot use `warp` at all as `warp::path` requires `p` to be `&'static str`.

I'm wondering if `warp` will ever support the use case where it's simply given a `&str` to route.

Thanks.

**Comment by seanmonstar** [comment]
I understand the use case, and would like to support it. The `path` filter could be changed to allow passing a `String` or something... but that would then prevent it from being `impl Filter + Copy`.

As a stopgap, you can probably achieve what you want by making using of `warp::path::param::<String>()`. You could then create dynamic filters like this:

```rust
let arg_path = clap.arg_something();

let clapped_path = warp::path::param()
    .and_then(move |param: String| {
        if param == arg_path {
            Ok(())
        } else {
            Err(warp::reject::not_found())
        }
    });
```

**Comment by erikdesjardins** [comment]
Another workaround: create a `&'static str` at runtime with [`Box::leak(string.into_boxed_str())`](https://play.rust-lang.org/?gist=076489af40d39885405f097063398fec&version=stable&mode=debug&edition=2015).
It will leak the string's memory, but if the server runs until process termination that's not a big deal.

**Comment by jsdw** [comment]
I ran into a related issue (working with `warp` on master which now supports `async`/`await`).

I'd like to be able to mount my app under an arbitrary path (eg "/foo/bar/wibble") so that it can happily be configured to coexist with other apps running (for example if I was to deploy it to k8s).

Using the `Box::leak` trick gets me as far as being able to configure a single path piece (eg "/foo") to mount the app underneath, but since slashes aren't allowed I can't supply a full path to mount the app underneath.

It would be nice to be able to use `String`s for paths in general, and also for slashes to work (perhaps using a new filter like full_path or somesuch? I'm not fully sure why they don't work already).
