### ISSUE TITLE
Best way to handle custom body filters?

### ISSUE THREAD

**Issue by novacrazy** [seanmonstar/warp#387]
I'd like to implement a MessagePack parsing filter similar to the Json filter, but it appears the Json filter relies on internal-only functionality and I would prefer to not duplicate code such as `is_content_type` and `filter_fn`. 

What do you suggest?

**Comment by novacrazy** [comment]
`is_content_type` looks like it could be made public if the opportunistic behavior was made configurable. After that, it's trivial to add the MessagePack parser.

**Comment by seanmonstar** [comment]
I'm not thrilled with the `mime` API, and so I've wanted to prevent exposing it publicly in warp. It could probably be written using `warp::header::optional::<Mime>("content-type")` for your MessagePack filter.

**Comment by novacrazy** [comment]
Hmm. Is there a reason why you don't use the optional header filter internally rather than having `is_content_type` at all?

**Comment by seanmonstar** [comment]
Oh right, I guess for a few reasons that made it easier to just use `filter_fn`:

- It returns `()`, and `map` or `and_then` would require an `untuple_one` on the end.
- I want to return an `UnsupportedMediaType` rejection, so I skip mapping from the `InvalidHeader` rejection.
- The `unsupported_media_type()` constructor isn't public... We could change that.

If you wanted the optimistic fallback, you'd use `optional()`. If not, you'd just use `header()`.

**Comment by Karrq** [comment]
I have a similar question, I'd like to encrypt/decrypt my request body using AES and so I wanted to make a filter for it to process the body before passing it to the rest of the route (if decrypted succesfully, otherwise just return a rejection), and also encrypt the reply on the way back.
I've tried to look into the documentation and the issues here on github but I couldn't find anything or where to start... I feel like this or unsealing `Wrap` might be what I need

**Comment by jxs** [comment]
@Karrq have you seen the [`warp::service`](https://docs.rs/warp/0.2.2/warp/fn.service.html#example) filter conversion? Helps on those cases, you can also find another example [here](https://github.com/seanmonstar/warp/pull/408#issuecomment-578157715)
