### ISSUE TITLE
Help understanding Filters and cloning of a DB pool

### ISSUE THREAD

**Issue by apiraino** [seanmonstar/warp#544]
Hello,

I'm new to Warp, sorry to open an issue about questions on Warp usage.

I'm basically trying to understand how Filters work. I'm reading the provided example of a TODO application:
https://github.com/seanmonstar/warp/blob/01299bf056629d98d4b0369dc8eb850286cc3be5/examples/todos.rs#L39-L46

My usecase for Filters would be to have a DB pool passed down to every endpoint. The endpoint then `.get()` a connection from the pool, does its job and releases it after returning the Reply.

I have a couple of questions about that example:
1) is there a recommended pattern to pass a reference to a DB pool down to a chain of Filters without cloning?
2) How does Filters chaining work? If I clone a db pool what is the cost at runtime? Do I have many clones all at once or the DB pool is only cloned when the Filter route matches?
3) Let's say I want to get a connection while chaining `.and()` for an endpoint. In the example I see a custom `with_db` Filter that does an additional clone.
https://github.com/seanmonstar/warp/blob/01299bf056629d98d4b0369dc8eb850286cc3be5/examples/todos.rs#L49-L56
My DB pool is async (using tokio-postgres), I'm trying to have a Filter `.await` a connection and then pass it on the endpoint, so I don't need to clone too much. Example (non working yet):
```
    /// POST /todos with JSON body
    pub fn todos_create(
        db: Db,
    ) -> impl Filter<Extract = impl warp::Reply, Error = warp::Rejection> + Clone {
        warp::path!("todos")
            .and(warp::post())
            .and(json_body())
            .and(warp::any().map(move || async { db.get_conn().await.unwrap() }))
            .and_then(handlers::create_todo) // create_todo has a db conn parameter
    }
```

Sorry to the lengthy questions and thanks for some guidance!

**Comment by nhynes** [comment]
I tried to do something similar and ended up solving it using `Arc`, but it's real messy. `Arc`s and `Arc`s everywhere. 

```rust
fn with_db(db: Arc<DbPool>) -> impl Filter<Extract = (Arc<DbPool>,), Error = Infallible> + Clone {
    warp::any().map(move || Arc::clone(&db_pool))
}
```

You'll note that `with_db` needs to take an owned `Arc` because it needs to `move` it into the closure (a ref might be dead by the time it gets invoked).

So, what I have in the filter ctor looks like

```rust
fn make_the_filters(db: Arc<DbPool>) -> impl Filter<Extract = (impl warp::Reply,), Error = Infallible> + Clone {
	let prefix = warp::path!("path" / "to" / "resource" / ..);

	let create = prefix
		.and(warp::path::end())
		.and(with_db(Arc::clone(db)))
		.and_then(create_thing);

	let get = prefix
		.and(warp::path::param())
		.and(with_db(Arc::clone(db)))
		.and_then(get_thing);

	create.or(get)
}
```

So this means that there'll be an `Arc` for every leaf of your filter tree , and then when the filter is actually matched, the closure will create another `Arc`. 

The `Arc`-creates-`Arc` thing is pretty ridiculous imo, so it's likely that I'm doing something wrong.

I guess one workaround is to take an `&'static Arc<_>`, but that requires some unsafe memory leakage in the `main` function. Of course, practically speaking, the DB queries will take more resources than the `Arc`s so I'm not losing sleep over it.

**Comment by apiraino** [comment]
very interesting thoughts, thanks for sharing. I had received a similar opinion a while ago and I agree that the (supposedly) perf. gain is not worth the effort and the decreased of readability.
