### ISSUE TITLE
ad-hoc custom filters

### ISSUE THREAD

**Issue by dakom** [seanmonstar/warp#555]
The usual case, which is everywhere in the examples, tends to start with a built-in filter and then proceed to call the various pipeline functions on that.

However, sometimes it's useful to create a new filter from nowhere. For example, to create a rejection filter in order to pass to `.or()`. Unless I'm mistaken, there's no simple way to do this, and we instead create a rejection filter by calling `.or_else()` - which requires an async callback that returns an Err type. 

What do you think about a macro that makes it easier to generate ad-hoc custom filters?

**Comment by rphmeier** [comment]
This seems to stem from one of the major pain points of the library, IMO, which is that traits such as `FilterBase` (which you need to implement custom filters) and `Wrap` are sealed. The easy things are easy but the hard things are not possible.

I don't think the macro you suggest is possible, since it would have to generate code of the form

```rust
impl FilterBase for MyType { }
```

which wouldn't be possible under Rust's visibility rules.

I think there are two ways forward:
  1. Expose the `FilterBase` trait. It seems to require an `Internal` struct that, with minor amendments, could be made uninstantiable outside of `warp`. This would have the downside that only one wrapped `FilterBase` could be invoked in a custom `FilterBase` implementation, which might be overly limiting. There's probably something you can do with a lifetime `'a` on Internal that allows `clone()`ing but prevents user implementations of `FilterBase` from hiding the `Internal` object away without `unsafe` code.
  2. Expose a `UserFilter` trait that implies a blanket `impl<T: UserFilter> FilterBase for T`. Given the purpose of `FilterBase` seems to be to protect the user from themselves, this approach does not seem in-line with the existing trait hierarchy.

**Comment by dakom** [comment]
What seems to be working for now is using `warp::any()` and then `and_then()`ing over that with closures + async Results. Seems to be okay, but haven't tested in-depth yet.

Does that basically make sense as a workaround?

**Comment by rphmeier** [comment]
Yeah, that seems like it should work for many cases

**Comment by seanmonstar** [comment]
This is actually the purpose of `warp::any()`. You can use that and chain anything else after it to get "custom" filters, without having to implement the trait (and access internal details).
