### ISSUE TITLE
warp 0.2.5 not compiler

### ISSUE THREAD

**Issue by zirill** [seanmonstar/warp#747]
**Version**
cargo 1.47.0
warp 0.2.5

**Platform**
ubuntu20.04

**Description**
`
error[E0277]: `S` cannot be shared between threads safely
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.2.5/src/filters/sse.rs:418:55
    |
418 |         let mut res = Response::new(Body::wrap_stream(body_stream));
    |                                                       ^^^^^^^^^^^ `S` cannot be shared between threads safely

`

**Comment by zirill** [comment]
magicians from 10 times everything gathered

**Comment by ParkMyCar** [comment]
For others that might be running into this issue, I think it's caused by two crates depending on two different versions of `hyper`. Personally I had a workspace where one crate had a dependency on `hyper 0.13.5` and another crate that used  `warp 0.2.5` which had a dependency on `hyper 0.13.9`. Breaking up this workspace so each crate had their own `Cargo.lock` fixed the issue for me. Upgrading your other dependency to use `hyper 0.13.9` would also probably work.
