### ISSUE TITLE
dir filter creates too many threads

### ISSUE THREAD

**Issue by pftbest** [seanmonstar/warp#755]
**Version**
warp v0.2.5

**Platform**
Linux openwrt 5.4.71 #0 SMP Tue Oct 20 00:14:45 2020 mips GNU/Linux

**Description**
I set core_threads to a low number however warp still creates more than 30 threads when tested with wrk. My router only has 2 cores why does warp need so many threads?

```Rust
#[tokio::main(core_threads = 2)]
async fn main() {
    let route = warp::fs::dir("/home/www");
    warp::serve(route).run((Ipv6Addr::UNSPECIFIED, 1337)).await;
}
```

**Comment by seanmonstar** [comment]
The file system operations use a blocking threadpool to read from disk. This is entirely based on `tokio::fs`. Tokio has 2 classes of threads, "core" and "blocking". If you really need to cap the limit, you use `#[tokio::main(max_threads = N)]`. However, note that since file system operations block a thread waiting for the data, it's common to have more of those threads than you have cores, since they are usually utilizing the CPU that much.

**Comment by pftbest** [comment]
I see, thanks. Sorry for the wrong report.
