### ISSUE TITLE
Add cargo.toml in examples

### ISSUE THREAD

**Issue by azzamsa** [seanmonstar/warp#781]
**Is your feature request related to a problem? Please describe.**
I am (and others https://github.com/seanmonstar/warp/issues/212, https://github.com/seanmonstar/warp/issues/314, [3](https://discord.com/channels/500028886025895936/671042482770935808/797789064443068437) ) having hard times running warp examples just because of wrong warp version or missing other dependencies in cargo.toml

**Describe the solution you'd like**
IMHO, it's better to add cargo.toml to warp examples. So people able to grab and run without any issue.
actix-web did the [same thing](https://github.com/actix/examples/tree/master/hello-world). They organize each example in its directory, ready to be run.

**Describe alternatives you've considered**
Explaining the required version and dependency in `examples/README.md`. But I prefer the latter.

**Comment by paulirotta** [comment]
First, the easy way:

`git clone https://github.com/seanmonstar/warp.git` and from the main directory type `cargo run --example websockets_chat`

A sample `Cargo.toml` for the above example is shown below. Other examples may have other requirements.

At the moment things are moving since Warp is being heavily updated to use the recently updated Tokio 1.0 async library.

`
[package]
name = "my-program-name"
version = "0.1.0"
authors = ["your-name <your-email@email.com>"]
edition = "2018"

[dependencies]
futures = { version = "0.3", default-features = false, features = ["alloc"] }
pretty_env_logger = "0.4"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"
tokio-util = { version = "0.6", features = ["io"] }
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"

# warp = "0.3  # Use this form after warp releases 0.3.0"
warp = {git = "https://github.com/seanmonstar/warp.git"} # Delete this line after warp 0.3 release
`

If you then want to make an own program using the above example, `cargo new my-program-name` and paste the example over the text cargo placed in `main.rs`.

If you are reading this after early 2020, replace the latest version number you see at https://crates.io/crates/warp . Opinions vary, but one habit is to use the first 2 digits of the library version number (`0.2`) instead of all 3. That way you can `cargo update` to minor releases of this and other libraries. In the Rust world, these minor updates are generally safe and give you various upstream improvements such as security fixes.
