### ISSUE TITLE
TLS? 

### ISSUE THREAD

**Issue by stephanbuys** [seanmonstar/warp#83]
Hi all, simple question - is warp ready to be run using TLS? I'm suspecting its a bit early for the question and that some `hyper` innards need to be exposed in the API first?

**Comment by stephanbuys** [comment]
Referencing #101 and re-opening. It would be great to get exposed to hyper in some way. Ideally a builder step. We're considering forking or patching `warp` to get to it in the meantime. @seanmonstar if this is something we can help with I am happy to jump in and start proposing PRs, please advise.

**Comment by seanmonstar** [comment]
I would like to provide TLS support built-in, but I haven't explored/decided on the exact details.

- I think I'd like to default to rustls, since I feel warp can be more opinionated that hyper.
- Someone suggest `tls-api`, which is intriguing, but I haven't investigated how mature the integration crates are.

-----

In the meantime, in order to support #101 and such, I believe some kind of `serve_incoming(impl Stream<Item = impl AsyncRead + AsyncWrite>)` could be added to `warp::Server`. That'd allow *any* transport layer to work.

**Comment by seanmonstar** [comment]
I'm leaning towards providing TLS via rustls.

**Comment by stephanbuys** [comment]
@seanmonstar it seems like a really good choice - great defaults and lots of support for CA certificate management.

**Comment by andy-rust** [comment]
As far as I understand, now there is the ability to use a custom "incoming" stream of connections with Server. 

Could anyone be so kind as to share a working Warp + TLS example using this feature?
