### ISSUE TITLE
generic trap

### ISSUE THREAD

**Issue by polariseye** [seanmonstar/warp#928]
**Version**
rust 1.57
warp 0.3.1

````
cargo tree |grep warp
│   │   │   └── warp v0.3.1
│   │   └── warp v0.3.1 (*)
└── warp v0.3.1 (*)
````
**Platform**
centos 7
memory 32G

**Description**
i develop  a business program with warp.but the binary is too large ,and build memory full with rust 1.57 . my app has 29 api. 

[short summary of the bug]
generic trap
I tried this code:
my app will reduce 600mb in dev build mod if i just delete my warp route code with 'rust 1.56.2'. and build success with rust 1.57

**Comment by apiraino** [comment]
To my understanding the core of the issue here is a regression in Rust 1.57 that concerns compile time and binary size.

Warp is only affected by these issues, the problem is [upstream](https://github.com/rust-lang/rust). The Rust lang project is working on fixing these regressions. You should see some improvement in Rust 1.58 and 1.59

In the meantime, please keep on using Rust 1.56.1 if the binary size generated in Rust 1.57 is a blocking issue for you.

**Comment by polariseye** [comment]
well~~it cost too much time to compile.i need cost 20 minutes to compile once in rust 1.56. it difficulty to me to fix bug.is the warp not suitable in work?

**Comment by apiraino** [comment]
Warp works fine, the issue is upstream and is being handled.

You might be interested in tuning [compile profiles](https://doc.rust-lang.org/cargo/reference/profiles.html) a little bit (if you have not yet done so) to get a quicker build and perhaps you can use `cargo check` for a full build only when strictly necessary.

Binary size on dev build may be annoying but compiling for release usually leads to acceptable binary size (in my experience).

Hope this helps!

**Comment by polariseye** [comment]
yes~i have forgot this issue.thank your for your remind
