### ISSUE TITLE
Catch  TLS error

### ISSUE THREAD

**Issue by cn-kali-team** [seanmonstar/warp#947]
**Version**
List the versions of all `warp` crates you are using. The easiest way to get
this information is using `cargo-tree`.

`cargo install cargo-tree`
(see install here: https://github.com/sfackler/cargo-tree)

Then:

`cargo tree | grep warp`
```
➜  ✗ cargo tree | grep warp
├── warp v0.3.2
```
**Platform**
The output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)
```
Linux LST 5.16.13-arch1-1 #1 SMP PREEMPT Tue, 08 Mar 2022 20:07:36 +0000 x86_64 GNU/Linux
```
**Description**
Enter your issue details here.
One way to structure the description:

[short summary of the bug]

I tried this code:

[code sample that causes the bug]
```
#[tokio::main]
async fn main() {
    use warp::Filter;

    // Match any request and return hello world!
    let routes = warp::any().map(|| "Hello, World!");

    warp::serve(routes)
        .tls()
        .cert_path("examples/tls/cert.pem")
        .key_path("examples/tls/key.rsa")
        .run(([127, 0, 0, 1], 3030))
        .await;
}
```

I expected to see this happen: [explanation]
```
thread '<unnamed>' panicked at 'error binding to 127.0.0.1:8000: certificate parse error', /home/kali-team/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/warp-0.3.2/src/server.rs:534:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Instead, this happened: [explanation]
When there is no certificate, I can catch the error

**Comment by apiraino** [comment]
Maybe it's just a typo, the code sample tries to bind on `127.0.0.1:3030` while the log says it cannot bind to `127.0.0.1:8000`

**Comment by cn-kali-team** [comment]
No, I just copied the sample code, but I changed the port or there was an error.

**Comment by cn-kali-team** [comment]
certificate parse error

**Comment by apiraino** [comment]
The error reported is from Tokio and is a runtime error of the Tokio executor thread when the file is not found (running `RUST_BACKTRACE=1 cargo run` shows the full Tokio backtrace).

I'm not sure if Warp could be able to catch this, I think because the work is handled by the underlying `openssl` library. I think you would get the same error for any file not found or invalid certificate.

One way I could solve this is adding a check if the files are actually where they should be; makes sense?

**Comment by adumbidiot** [comment]
Not really a work-around though, as this panic is also triggered for invalid certificates.

**Comment by vidhatha** [comment]
@cn-kali-team I am facing the same issue as well. Did you figure out the fix?

**Comment by vidhatha** [comment]
@seanmonstar any idea why this occurs?

**Comment by sm13** [comment]
I faced the same issue and found the problem to be that the certificate path was incorrect. In my case, using Cargo, the path was relative to the Cargo root. Assuming the code from the OP had the file inside a `src` folder, the files had to be a level above `src`, not inside it. 
```
├── examples
│   └── tls
│       ├── cert.pem
│       └── key.rsa
└── src
    └── main.rs
```
It may be simpler than that, for instance, in the example above the name may have been `cert.crt` rather than `cert.pem`.
